version: 2
jobs:
  build:
    docker:
      - image: circleci/node:chakracore-10.1
    parallelism: 1
    working_directory: ~/rossta/connect-four-vue
    steps:
      - checkout
      - attach_workspace:
          at: ~/rossta/connect-four-vue
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - save_cache:
          paths:
            - ./node_modules
      - run: yarn test:unit
      - run: yarn lint
      - run: yarn test:e2e
      - persist_to_workspace:
          root: .
          paths: dist
