version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.8.0
    parallelism: 1
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - restore_cache:
          key: v1-yarn-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          key: v1-yarn-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run: yarn lint
      - persist_to_workspace:
          root: .
          paths: dist

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
          filters:
            branches:
              only: master
